In [3]:
!python --version
!pip --version
!pip install -U pip setuptools wheel

Python 3.9.23
pip 25.3 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
Requirement already satisfied: pip in /usr/local/lib/python3.9/dist-packages (25.3)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (59.6.0)
Collecting setuptools
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.37.1)
Collecting wheel
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Downloading setuptools-80.9.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 19.5 MB/s  0:00:00
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel, setuptools
  Attempting uninstall: wheel
    Found existing installation: wheel 0.37.1
    Uninstalling wheel-0.37.1:
      Successfully uninstalled wheel-0.37.1
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Uninstalling setuptools-59.6.0:
      Successfully uninstalled setuptools-59.6.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [setuptools]2 [setuptools]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.15.0 which is incompatible.
Successfully installed setuptools-80.9.0 wheel-0.45.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [1]:
!pip install -r requirements.txt
# !pip install -U sentencepiece protobuf

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: pillow==10.4.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (10.4.0)
Requirement already satisfied: tensorflow==2.15.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (2.15.1)
Requirement already satisfied: torch==2.2.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (2.2.2)
Requirement already satisfied: torchvision==0.17.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (0.17.2)
Requirement already satisfied: diffusers==0.30.3 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (0.30.3)
Requirement already satisfied: transformers==4.44.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 11)) (4.44.2)
Requirement already satisfied: accelerate==0.33.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 12)) (0.33.0)
Requirement already satisfied: safetensors==0.4.4 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 13)) (0.4.4)
Requirement already satisfied: peft==0.17.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 14)) (0.17.0)
Requirement already satisfied: huggingface-hub==0.25.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 16)) (0.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.9/dist-packages (from pandas==2.2.2->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas==2.2.2->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.9/dist-packages (from pandas==2.2.2->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (3.14.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.3.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (0.3.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (4.25.8)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (59.6.0)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (4.15.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (1.14.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (0.37.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (1.73.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow==2.15.1->-r requirements.txt (line 5)) (2.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (3.18.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.9/dist-packages (from torch==2.2.2->-r requirements.txt (line 7)) (2.2.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.9/dist-packages (from diffusers==0.30.3->-r requirements.txt (line 10)) (8.7.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.9/dist-packages (from diffusers==0.30.3->-r requirements.txt (line 10)) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from diffusers==0.30.3->-r requirements.txt (line 10)) (2.32.4)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from transformers==4.44.2->-r requirements.txt (line 11)) (6.0.2)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.9/dist-packages (from transformers==4.44.2->-r requirements.txt (line 11)) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.9/dist-packages (from transformers==4.44.2->-r requirements.txt (line 11)) (4.66.5)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/dist-packages (from accelerate==0.33.0->-r requirements.txt (line 12)) (7.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.9/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.2.2->-r requirements.txt (line 7)) (12.9.86)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow==2.15.1->-r requirements.txt (line 5)) (0.37.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (2.40.3)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (3.1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->diffusers==0.30.3->-r requirements.txt (line 10)) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->diffusers==0.30.3->-r requirements.txt (line 10)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->diffusers==0.30.3->-r requirements.txt (line 10)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->diffusers==0.30.3->-r requirements.txt (line 10)) (2025.7.14)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata->diffusers==0.30.3->-r requirements.txt (line 10)) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2->torch==2.2.2->-r requirements.txt (line 7)) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from sympy->torch==2.2.2->-r requirements.txt (line 7)) (1.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.9/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow==2.15.1->-r requirements.txt (line 5)) (3.2.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python3 -m pip install --upgrade pip

In [1]:
from pathlib import Path

# -------- SET PATHS --------
IMAGES_ROOT   = Path("images/test")      # images_root/class/*.jpg
ANN_ROOT      = Path("test_annotations")         # ann_root/class/*.xml
FAKES_ROOT    = Path("obj_labels_to_fakes(test)")       # output fakes_root/class/fake_<orig>.jpg

MODEL_H5      = Path("model_INCEPTIONV3_sun10_jul23.h5")
REAL_ACT_CSV  = Path("preds_of_64Neurons_denseLayer_training.csv")  # real activations (filenames + "0".."63")


# -------- LIMITS --------
PROMPT_TMPL = (
    "A realistic photo of a {cls} scene, natural lighting, high detail, sharp focus, "
    "containing {objs}."
)
NEG_PROMPT  = "cartoon, illustration, painting, drawing, blurry, low quality, watermark, text, logo, distorted, deformed, unrealistic"

MAX_GEN_SIZE = 500
N_NEURONS = 64

# -------- GENERATION PARAMS --------
SDXL_MODEL_ID = "stabilityai/stable-diffusion-xl-base-1.0"
STEPS = 30
GUIDANCE = 6.5
H, W = 768, 768
BASE_SEED = 12345

In [2]:
import re
import xml.etree.ElementTree as ET
from pathlib import Path
import pandas as pd


def parse_objects(xml_path, dedupe=True):
    root = ET.parse(xml_path).getroot()
    labels = []
    for obj in root.findall("object"):
        name = obj.findtext("name")
        if not name:
            continue
        name = re.sub(r"\s+", " ", name).strip()
        if name:
            labels.append(name)

    if not dedupe:
        return labels

    seen, uniq = set(), []
    for x in labels:
        if x not in seen:
            uniq.append(x); seen.add(x)
    return uniq


# def ultra_compact(o: str) -> str:
#     o = o.lower().strip()
#     o = re.sub(r"\s+", " ", o)

#     # semantic-preserving shorthand
#     o = o.replace(" occluded", " occl")
#     o = o.replace(" partially", " part")
#     o = o.replace(" visible", "")

#     # remove spaces completely (big token saver)
#     o = o.replace(" ", "")

#     # keep only letters+digits
#     o = re.sub(r"[^a-z0-9]", "", o)
#     return o

# def build_objs_string(objects: list[str]) -> str:
#     seen = set()
#     out = []
#     for o in objects:
#         c = ultra_compact(o)
#         if c and c not in seen:
#             out.append(c)
#             seen.add(c)
#     # use a single delimiter that tends to tokenize compactly
#     return ",".join(out)

# def build_prompt(cls: str, objects: list[str]) -> str:
#     objs = build_objs_string(objects)
#     return f"A realistic photo of a {cls} interior containing {objs}, natural lighting, high detail, sharp focus."

In [5]:
# Load 3 CSVs and build the must-include object list
import pandas as pd
import re
from pathlib import Path

CSV_1 = Path("verification_summary_1 (test).csv")  # available
# CSV_2 = Path("evaluation_combined_(summary_2).csv")  # <-- re-upload + set correct path
# CSV_3 = Path("evaluation_combined_(summary_3).csv")   # <-- re-upload + set correct path


def split_concepts(s):
    if pd.isna(s):
        return []
    s = str(s).strip().lower()

    # split on separators
    parts = []
    for sep in [";", ",", "|"]:
        if sep in s:
            parts = [x.strip() for x in s.split(sep) if x.strip()]
            break
    else:
        parts = [s]

    out = []
    for p in parts:
        subs = p.split("_and_") if "_and_" in p else [p]
        for x in subs:
            x = x.replace("_", " ")              # dish_rack -> dish rack
            x = re.sub(r"\s+", " ", x).strip()   # normalize spaces
            if x:
                out.append(x)
    return out

def load_required_set(csv_paths):
    req = set()
    for p in csv_paths:
        df = pd.read_csv(p)
        if "ecii_concepts" not in df.columns:
            raise ValueError(f"{p} missing 'ecii concepts' column.")
        for val in df["ecii_concepts"].tolist():
            for obj in split_concepts(val):
                req.add(obj)
    return req

REQUIRED_SET = load_required_set([CSV_1])
print("Required objects:", len(REQUIRED_SET))

Required objects: 21

In [6]:
import pandas as pd
from pathlib import Path

def normalize_label(x: str) -> str:
    x = str(x).strip().lower()
    x = re.sub(r"\s+", " ", x).strip()
    return x

def build_prompt_from_xml(cls, xml_objects, required_set):
    # normalize XML objects for matching, but keep original text for prompt if you want
    xml_norm = [normalize_label(o) for o in xml_objects]

    # priority = XML ∩ REQUIRED
    priority = []
    other = []
    seen = set()

    for orig, norm in zip(xml_objects, xml_norm):
        if norm in seen:
            continue
        seen.add(norm)
        if norm in required_set:
            priority.append(orig)   # keep original form like "dish rack"
        else:
            other.append(orig)

    # Put priority first, then others (others may be truncated)
    ordered = priority + other

    objs = ", ".join(ordered)
    return PROMPT_TMPL.format(cls=cls, objs=objs)

def build_manifest(images_root: Path, ann_root: Path, required_set):
    rows = []
    for cls_dir in sorted([p for p in images_root.iterdir() if p.is_dir()]):
        cls = cls_dir.name
        ann_cls = ann_root / cls
        if not ann_cls.exists():
            continue

        for img_path in sorted(cls_dir.glob("*")):
            if img_path.suffix.lower() not in [".jpg", ".jpeg", ".png", ".bmp", ".webp"]:
                continue

            xml_path = ann_cls / (img_path.stem + ".xml")
            if not xml_path.exists():
                continue

            xml_objs = parse_objects(xml_path, dedupe=False)  # keep order from XML
            if not xml_objs:
                continue

            prompt = build_prompt_from_xml(cls, xml_objs, required_set)

            rows.append({
                "class": cls,
                "real_rel": f"{cls}/{img_path.name}",
                "real_path": str(img_path),
                "xml_path": str(xml_path),
                "xml_objects": ";".join(xml_objs),
                "prompt": prompt,
            })

    return pd.DataFrame(rows)

manifest = build_manifest(IMAGES_ROOT, ANN_ROOT, REQUIRED_SET)
print("Manifest rows:", len(manifest))
manifest.head()

Manifest rows: 793

,class,real_rel,real_path,xml_path,xml_objects,prompt
0,bathroom,bathroom/sun_aacopdmawrifxaso.jpg,images/test/bathroom/sun_aacopdmawrifxaso.jpg,test_annotations/bathroom/sun_aacopdmawrifxaso...,toilet paper;toilet;bathtub crop;floor;wall;to...,"A realistic photo of a bathroom scene, natural..."
1,bathroom,bathroom/sun_aajnjyglytmisoki.jpg,images/test/bathroom/sun_aajnjyglytmisoki.jpg,test_annotations/bathroom/sun_aajnjyglytmisoki...,wall;wall;wall;ceiling;wall;wall;shower;rail;c...,"A realistic photo of a bathroom scene, natural..."
2,bathroom,bathroom/sun_aameczztdzpctgas.jpg,images/test/bathroom/sun_aameczztdzpctgas.jpg,test_annotations/bathroom/sun_aameczztdzpctgas...,toilet;bidet;sink;towel;faucet;faucet;floor;wa...,"A realistic photo of a bathroom scene, natural..."
3,bathroom,bathroom/sun_aaoplqapkfcogulx.jpg,images/test/bathroom/sun_aaoplqapkfcogulx.jpg,test_annotations/bathroom/sun_aaoplqapkfcogulx...,chair;picture frame;picture frame;shower scree...,"A realistic photo of a bathroom scene, natural..."
4,bathroom,bathroom/sun_aaoxywoasynoalhw.jpg,images/test/bathroom/sun_aaoxywoasynoalhw.jpg,test_annotations/bathroom/sun_aaoxywoasynoalhw...,wall;wall;wall;curtain;stall shower;towel;mirr...,"A realistic photo of a bathroom scene, natural..."

In [7]:
manifest.iloc[0]["prompt"]

'A realistic photo of a bathroom scene, natural lighting, high detail, sharp focus, containing toilet, toilet paper, bathtub crop, floor, wall, towel, Sally, paper.'

In [3]:
# # manifest.to_csv("manifest.csv", index=False)

# import pandas as pd
# manifest = pd.read_csv("manifest.csv")

In [8]:
from transformers import CLIPTokenizer

tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")
MAX_TOKENS = 77

def prompt_token_len(tokenizer, text: str) -> int:
    ids = tokenizer(text, return_tensors="pt", truncation=False).input_ids
    return int(ids.shape[-1])

manifest2 = manifest.copy()
manifest2["prompt_tokens"] = [prompt_token_len(tokenizer, p) for p in manifest2["prompt"]]
manifest2["will_truncate"] = manifest2["prompt_tokens"] > MAX_TOKENS

trunc_df = manifest2[manifest2["will_truncate"]].copy()
trunc_df.to_csv("truncated_prompts.csv", index=False)

print("Saved: truncated_prompts.csv")
print("Truncated:", len(trunc_df), "out of", len(manifest2))

trunc_df.sort_values("prompt_tokens", ascending=False)[["real_rel","prompt_tokens","prompt"]].head(10)

tokenizer_config.json:   0%|          | 0.00/905 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Token indices sequence length is longer than the specified maximum sequence length for this model (80 > 77). Running this sequence through the model will result in indexing errors

Saved: truncated_prompts.csv
Truncated: 79 out of 793

,real_rel,prompt_tokens,prompt
535,kitchen/sun_alvoexkareccqxgq.jpg,158,"A realistic photo of a kitchen scene, natural ..."
518,kitchen/sun_ajagcmjkbndzjfgv.jpg,147,"A realistic photo of a kitchen scene, natural ..."
496,kitchen/sun_afqpfzmhhuegedtn.jpg,142,"A realistic photo of a kitchen scene, natural ..."
569,kitchen/sun_ayakdnbiuvnibwap.jpg,138,"A realistic photo of a kitchen scene, natural ..."
561,kitchen/sun_aufggmchclraycgm.jpg,132,"A realistic photo of a kitchen scene, natural ..."
517,kitchen/sun_aizcycyyvgfcdnzp.jpg,125,"A realistic photo of a kitchen scene, natural ..."
557,kitchen/sun_arvuykssgbdzaavk.jpg,124,"A realistic photo of a kitchen scene, natural ..."
506,kitchen/sun_ahhgskanediiligq.jpg,120,"A realistic photo of a kitchen scene, natural ..."
508,kitchen/sun_ahtnfrjwdoxeudea.jpg,120,"A realistic photo of a kitchen scene, natural ..."
485,kitchen/sun_acpufsxakyzrtcti.jpg,120,"A realistic photo of a kitchen scene, natural ..."

In [9]:
import pandas as pd

MAX_TOKENS = 77

def prompt_token_len(tokenizer, text: str) -> int:
    ids = tokenizer(text, return_tensors="pt", truncation=False).input_ids
    return int(ids.shape[-1])

token_lens = []
will_truncate = []

for p in manifest["prompt"]:
    n = prompt_token_len(tokenizer, p)
    token_lens.append(n)
    will_truncate.append(n > MAX_TOKENS)

manifest = manifest.copy()
manifest["prompt_tokens"] = token_lens
manifest["will_truncate"] = will_truncate

# save truncated prompts
trunc_df = manifest[manifest["will_truncate"]]
trunc_df.to_csv("truncated_prompts.csv", index=False)

print("Saved: truncated_prompts.csv")
print("Truncated:", len(trunc_df), "out of", len(manifest))

# preview longest ones
trunc_df.sort_values("prompt_tokens", ascending=False)[
    ["real_rel", "prompt_tokens", "prompt"]
].head(10)

Saved: truncated_prompts.csv
Truncated: 79 out of 793

,real_rel,prompt_tokens,prompt
535,kitchen/sun_alvoexkareccqxgq.jpg,158,"A realistic photo of a kitchen scene, natural ..."
518,kitchen/sun_ajagcmjkbndzjfgv.jpg,147,"A realistic photo of a kitchen scene, natural ..."
496,kitchen/sun_afqpfzmhhuegedtn.jpg,142,"A realistic photo of a kitchen scene, natural ..."
569,kitchen/sun_ayakdnbiuvnibwap.jpg,138,"A realistic photo of a kitchen scene, natural ..."
561,kitchen/sun_aufggmchclraycgm.jpg,132,"A realistic photo of a kitchen scene, natural ..."
517,kitchen/sun_aizcycyyvgfcdnzp.jpg,125,"A realistic photo of a kitchen scene, natural ..."
557,kitchen/sun_arvuykssgbdzaavk.jpg,124,"A realistic photo of a kitchen scene, natural ..."
506,kitchen/sun_ahhgskanediiligq.jpg,120,"A realistic photo of a kitchen scene, natural ..."
508,kitchen/sun_ahtnfrjwdoxeudea.jpg,120,"A realistic photo of a kitchen scene, natural ..."
485,kitchen/sun_acpufsxakyzrtcti.jpg,120,"A realistic photo of a kitchen scene, natural ..."

## SDXL Pipeline

In [11]:
import torch
from diffusers import StableDiffusionXLPipeline
from PIL import Image

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = torch.float16 if DEVICE == "cuda" else torch.float32

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=DTYPE,
    variant="fp16" if DEVICE == "cuda" else None,
).to(DEVICE)

try:
    pipe.enable_xformers_memory_efficient_attention()
except Exception:
    pass
pipe.enable_attention_slicing()

def resize_for_saving(img: Image.Image, max_size=MAX_GEN_SIZE):
    w, h = img.size
    if w <= max_size and h <= max_size:
        return img
    scale = min(max_size / w, max_size / h)
    return img.resize((int(w*scale), int(h*scale)), Image.BICUBIC)

STEPS = 30
GUIDANCE = 6.5
H, W = 768, 768
BASE_SEED = 12345

FAKES_ROOT.mkdir(parents=True, exist_ok=True)

def generate_one(prompt: str, out_path: Path, seed: int):
    gen = torch.Generator(device=DEVICE).manual_seed(seed)
    img = pipe(
        prompt=prompt,
        negative_prompt=NEG_PROMPT,
        num_inference_steps=STEPS,
        guidance_scale=GUIDANCE,
        height=H,
        width=W,
        generator=gen,
    ).images[0]
    img = resize_for_saving(img, max_size=MAX_GEN_SIZE)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path, quality=95)

for i, row in manifest.iterrows():
    cls = row["class"]
    real_name = Path(row["real_path"]).name
    out_path = FAKES_ROOT / cls / f"fake_{real_name}"
    if out_path.exists():
        continue
    generate_one(row["prompt"], out_path, seed=BASE_SEED + i)

print("Done generating fakes:", FAKES_ROOT)

Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (80 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['bath sponge.']
Token indices sequence length is longer than the specified maximum sequence length for this model (80 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['bath sponge.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['door crop, soap, soap dish, bottle.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['door crop, soap, soap dish, bottle.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['vase, flowers, faucet, tap wrench, jar, sconce.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['vase, flowers, faucet, tap wrench, jar, sconce.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor, carpet occluded.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor, carpet occluded.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['curtain, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['curtain, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cabinet crop, door crop, curtain occluded, curtain rod, floor, pillow, carpet crop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cabinet crop, door crop, curtain occluded, curtain rod, floor, pillow, carpet crop.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor, chandelier.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor, chandelier.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cluded.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cluded.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pot, plant, tray, cup, newspaper, floor, carpet, candleholder, box, ceiling lamp.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['pot, plant, tray, cup, newspaper, floor, carpet, candleholder, box, ceiling lamp.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ded, cushion, floor, ceiling lamp crop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ded, cushion, floor, ceiling lamp crop.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, pillow, floor, rug.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, pillow, floor, rug.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['door, desk crop, floor, switch, books, carpet crop, grille.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['door, desk crop, floor, switch, books, carpet crop, grille.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['box, floor, desk lamp occluded.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['box, floor, desk lamp occluded.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['left.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['left.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['right.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['right.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['window, car _ back, car _ top _ back, car _ right.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['window, car _ back, car _ top _ back, car _ right.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flowers, ceiling lamp crop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flowers, ceiling lamp crop.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', table, plant pot, plant, chandelier crop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', table, plant pot, plant, chandelier crop.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', chair occluded, chair, rug, extractor hood, cabinet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', chair occluded, chair, rug, extractor hood, cabinet.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ope, artichoke, pineapple, wall, floor, countertop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ope, artichoke, pineapple, wall, floor, countertop.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', ceiling lamp.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', ceiling lamp.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['outlet, table, grille.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['outlet, table, grille.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['glass occluded, chandelier.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['glass occluded, chandelier.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', jug, cup, side table, floor, wood art, window frame, wall, glass in door, glass, cabinet door.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', jug, cup, side table, floor, wood art, window frame, wall, glass in door, glass, cabinet door.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', flower.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', flower.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['chest, plant, rug, place mat occluded.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['chest, plant, rug, place mat occluded.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['crop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['crop.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ceiling lamp, mug, ceiling lamp crop, switch.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ceiling lamp, mug, ceiling lamp crop, switch.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['baseboard, cabinet occluded, floor, chair occluded, table crop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['baseboard, cabinet occluded, floor, chair occluded, table crop.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['outlet, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['outlet, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', ceiling lamp, pitcher, window occluded, plant, pot occluded, switch, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', ceiling lamp, pitcher, window occluded, plant, pot occluded, switch, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['kettle, tray, door, chair, floor, plant pot crop, plant, pot, candleholder, place mat.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['kettle, tray, door, chair, floor, plant pot crop, plant, pot, candleholder, place mat.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['fork, knife, napkin, fork crop, sink, faucet, toaster, pitcher, paper roll, stove, soap dispenser, plant pot, plant, box, floor, jar, jar occluded, can.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['fork, knife, napkin, fork crop, sink, faucet, toaster, pitcher, paper roll, stove, soap dispenser, plant pot, plant, box, floor, jar, jar occluded, can.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, saucepan occluded, frying pan, lid, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, saucepan occluded, frying pan, lid, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', radio crop, bread box, cabinet crop, floor, switch.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', radio crop, bread box, cabinet crop, floor, switch.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flowers, ceiling lamp crop, sink occluded, sink, faucet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flowers, ceiling lamp crop, sink occluded, sink, faucet.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wall.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['wall.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', grinder, scales.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', grinder, scales.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, apple, oven occluded, bottle occluded, bowl, floor, door frame, chair occluded, table occluded, basket occluded, vase occluded, refrigerator, flowers, sink, faucet, plate, plate crop, bottles, cup, mug, ceiling lamp.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, apple, oven occluded, bottle occluded, bowl, floor, door frame, chair occluded, table occluded, basket occluded, vase occluded, refrigerator, flowers, sink, faucet, plate, plate crop, bottles, cup, mug, ceiling lamp.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', wall, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', wall, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['outlet, microwave, shelf, picture, picture occluded, ceiling lamp, stove, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['outlet, microwave, shelf, picture, picture occluded, ceiling lamp, stove, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ded, vase, candleholder, dread flowers, bowl, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ded, vase, candleholder, dread flowers, bowl, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cluded, bucket occluded, table, plant, door frame, door, door occluded, microwave, stove, drawers, refrigerator crop, cabinet crop, dishwasher crop, floor, switch, outlet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cluded, bucket occluded, table, plant, door frame, door, door occluded, microwave, stove, drawers, refrigerator crop, cabinet crop, dishwasher crop, floor, switch, outlet.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', cup, knife, chair occluded, chair crop, ceiling lamp.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', cup, knife, chair occluded, chair crop, ceiling lamp.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['worktop, stove, drawers, cabinet crop, screen, coffee maker, jar, sink, faucet, window crop, outlet, microwave, oven occluded, refrigerator, cabinde, dishwasher, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['worktop, stove, drawers, cabinet crop, screen, coffee maker, jar, sink, faucet, window crop, outlet, microwave, oven occluded, refrigerator, cabinde, dishwasher, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sils canister, coffee pot, sink, faucet, worktop, cabinet occluded, tray, bowl, oven, drawer, drawers, floor, flower, clock, outlet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['sils canister, coffee pot, sink, faucet, worktop, cabinet occluded, tray, bowl, oven, drawer, drawers, floor, flower, clock, outlet.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, bottle occluded, kitchen island, dishcloth, door frame, door, chair occluded, chair, bowl, fruits, rug, table occluded, chair crop, floor, switch, ceiling lamp.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, bottle occluded, kitchen island, dishcloth, door frame, door, chair occluded, chair, bowl, fruits, rug, table occluded, chair crop, floor, switch, ceiling lamp.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', mug occluded, knife set, drawers, worktop, stove, microwave, toaster, bowl occluded, pot, glass occluded, glass, refrigerator, cabinet, sink occluded, frying pan occluded, frying pan, bowls, bowls occluded, dishcloth, pepper, salt, floor, outlet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', mug occluded, knife set, drawers, worktop, stove, microwave, toaster, bowl occluded, pot, glass occluded, glass, refrigerator, cabinet, sink occluded, frying pan occluded, frying pan, bowls, bowls occluded, dishcloth, pepper, salt, floor, outlet.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', rack, wall, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', rack, wall, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', bottle, cabinet crop.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', bottle, cabinet crop.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['curtain, plant pot.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['curtain, plant pot.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', rug, knife set, sink, outlet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', rug, knife set, sink, outlet.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor, bowl, fruits, electric pitcher, outlet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor, bowl, fruits, electric pitcher, outlet.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tea, ceiling lamps, wine glasses, books, basket of vegtables, bottles, basket of potatos, basket of onions, tins of tea, decorative bottle, crackers, cup, extractor hood, jar, ladle, magazine, towel, stool, cabinet, pot holder, oil jar, garlic, vinegar jar, garlic braid, basket, ceiling, wall, cabinets, worktop, sculpture.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['tea, ceiling lamps, wine glasses, books, basket of vegtables, bottles, basket of potatos, basket of onions, tins of tea, decorative bottle, crackers, cup, extractor hood, jar, ladle, magazine, towel, stool, cabinet, pot holder, oil jar, garlic, vinegar jar, garlic braid, basket, ceiling, wall, cabinets, worktop, sculpture.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', window, floor, trash compactor, wall, kitchen island.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', window, floor, trash compactor, wall, kitchen island.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['coffee maker, scales, jars, door knob, stove, wall, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['coffee maker, scales, jars, door knob, stove, wall, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['bottle, faucet, canister, bottle occluded.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['bottle, faucet, canister, bottle occluded.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['kitchen island, wall, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['kitchen island, wall, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['coffee maker, outlet.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['coffee maker, outlet.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['bowl of fruit, plate of salad, peach, magazine, teapot, cabinet occluded, large rabbit, rabbit, drawers, cabinet, worktop, stove, chandelier, potted plant, floor, wall, plant pot, flowers.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['bowl of fruit, plate of salad, peach, magazine, teapot, cabinet occluded, large rabbit, rabbit, drawers, cabinet, worktop, stove, chandelier, potted plant, floor, wall, plant pot, flowers.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['top, ceiling lamp crop, refrigerator, ceiling, wall, kitchen island.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['top, ceiling lamp crop, refrigerator, ceiling, wall, kitchen island.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', coffee maker, pot, stove, ceiling lamp, jug, statue, plant, clock, stool occluded, pottery, mug, saltcellar, cup, teapot.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', coffee maker, pot, stove, ceiling lamp, jug, statue, plant, clock, stool occluded, pottery, mug, saltcellar, cup, teapot.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['napkin, bread box, tin, wood paddle, wreath, stack of plates, potted plant, towel, roman shade, decorative plate, window, cutting board, wall, jar of utencils, cook books, spice rack, worktop, floor, object, counter.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['napkin, bread box, tin, wood paddle, wreath, stack of plates, potted plant, towel, roman shade, decorative plate, window, cutting board, wall, jar of utencils, cook books, spice rack, worktop, floor, object, counter.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', plant, teapot, cheese, ladle, outlet, kettle, microwave, cup, jar, dishes, mugs, pitcher, object, dish, ceiling, cabinet, refrigerator, china hutch, worktop, cabinets, stove top, floor, curtains, wall, pasta jar, molding, back splash.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', plant, teapot, cheese, ladle, outlet, kettle, microwave, cup, jar, dishes, mugs, pitcher, object, dish, ceiling, cabinet, refrigerator, china hutch, worktop, cabinets, stove top, floor, curtains, wall, pasta jar, molding, back splash.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ceiling, wall, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['ceiling, wall, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flowers, tree, vase, flowers, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['flowers, tree, vase, flowers, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['floor, table occluded.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['floor, table occluded.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', stone figure, floor, candle.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', stone figure, floor, candle.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cluded, vase, flowers.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cluded, vase, flowers.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', cushion, vest, fish, birdcage, wall, basket, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', cushion, vest, fish, birdcage, wall, basket, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, bottle.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['occluded, bottle.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', end table, chandelier, ceiling, candlestick, roman shade, window, desk lamp crop, frame, dish, wall, floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', end table, chandelier, ceiling, candlestick, roman shade, window, desk lamp crop, frame, dish, wall, floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor.']
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', floor.']

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

  0%|          | 0/30 [00:00<?, ?it/s]

Done generating fakes: obj_labels_to_fakes(test)

In [15]:
# --- Get activations for ALL fake images under out_fake/<class>/<image> ---

import os, csv
from pathlib import Path
import numpy as np
from PIL import Image
import tensorflow as tf
from tensorflow.keras.models import load_model

OUT_FAKE_ROOT   = Path("obj_labels_to_fakes(test)")                      # input root with fakes
MODEL_PATH      = "model_INCEPTIONV3_sun10_jul23.h5"    # your .h5 model
OUT_CSV_PATH    = "[obj_labels_to_fakes]fake_activations(test).csv"                # output CSV

# 1) Load model once and build penultimate (assumes last-2 is Dense(64))
model = load_model(MODEL_PATH, compile=False)
penultimate = tf.keras.Model(inputs=model.input, outputs=model.layers[-2].output)

# 2) Infer input size (H, W, C)
in_shape = model.input_shape
if isinstance(in_shape, list):
    in_shape = in_shape[0]
_, H_in, W_in, C_in = in_shape

# 3) Prepare CSV
fieldnames = ["filenames"] + [str(i) for i in range(64)]
with open(OUT_CSV_PATH, "w", newline="", encoding="utf-8") as fcsv:
    writer = csv.DictWriter(fcsv, fieldnames=fieldnames)
    writer.writeheader()

    # Walk class folders
    for cls_dir in sorted([d for d in OUT_FAKE_ROOT.iterdir() if d.is_dir()]):
        cls = cls_dir.name
        for img_path in sorted(cls_dir.glob("*.*")):
            if img_path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
                continue

            rel_filename = f"{cls}/{img_path.name}"

            # Load & preprocess
            try:
                img = Image.open(img_path).convert("RGB")
                img = img.resize((W_in, H_in), Image.BICUBIC)
                x = tf.keras.utils.img_to_array(img).astype("float32")
                if C_in == 1:
                    x = tf.image.rgb_to_grayscale(x)
                x = x / 255.0
                x = np.expand_dims(x, 0)  # (1,H,W,C)
            except Exception as e:
                print(f"[load/prep] {rel_filename}: {e}")
                continue

            # Forward pass to penultimate
            try:
                act = penultimate.predict(x, verbose=0)[0]  # shape (64,)
            except Exception as e:
                print(f"[predict] {rel_filename}: {e}")
                continue

            # Write one row
            row = {"filenames": rel_filename}
            for j in range(64):
                row[str(j)] = float(act[j])
            writer.writerow(row)

print(f"[done] wrote activations for fakes -> {OUT_CSV_PATH}")

[done] wrote activations for fakes -> [obj_labels_to_fakes]fake_activations(test).csv

In [21]:
# --- Step 7: fired-counts utilities (stdlib CSV + numpy) ---
import csv
import numpy as np

# minimal error log (list of dicts); use if you want to capture issues
ERRORS = []
def log_error(stage, item, exc):
    msg = f"[{stage}] {item}: {type(exc).__name__}: {exc}"
    print(msg)
    ERRORS.append({"stage": stage, "item": str(item), "error": f"{type(exc).__name__}: {exc}"})

def load_csv_as_dicts(path):
    with open(path, "r", newline="", encoding="utf-8") as f:
        rdr = csv.DictReader(f)
        rows = [r for r in rdr]
        header = rdr.fieldnames
    return header, rows

def find_filename_column(header):
    for cand in ("filenames", "filename", "file", "path"):
        if cand in header:
            return cand
    raise RuntimeError("No filename column found (looked for: filenames/filename/file/path)")

def ensure_neuron_columns(header, n=64):
    cols = [str(i) for i in range(n)]
    missing = [c for c in cols if c not in header]
    if missing:
        raise RuntimeError(f"Missing neuron columns in CSV, e.g., {missing[:5]}")
    return cols

def compute_threshold_from_real(real_rows, neuron_cols, ratio=0.8):
    # Per-neuron max across *all real* rows, then 0.8×
    first = True
    max_act = None
    for r in real_rows:
        vals = np.array([float(r[c]) for c in neuron_cols], dtype=np.float64)
        if first:
            max_act = vals
            first = False
        else:
            max_act = np.maximum(max_act, vals)
    if max_act is None:
        raise RuntimeError("Real CSV had no rows.")
    return ratio * max_act  # numpy array shape (64,)

def count_fired(vec, threshold):
    # vec, threshold are np arrays shape (64,)
    return int(np.sum(vec >= threshold))


def _candidate_fake_keys(orig_fname):
    """
    Given e.g. 'living_room/sun_abc.jpg', try keys commonly seen in fake CSVs:
      1) same path, basename prefixed: 'living_room/fake_sun_abc.jpg'
      2) whole relpath prefixed:       'fake_living_room/sun_abc.jpg' (rare but try)
      3) just basename prefixed:       'fake_sun_abc.jpg'
      4) exact original (in case CSV already matches)
    """
    d = os.path.dirname(orig_fname)
    b = os.path.basename(orig_fname)
    pref_b = f"fake_{b}"

    cand = []
    # same dir, prefixed basename
    cand.append(os.path.join(d, pref_b) if d else pref_b)
    # whole relpath prefixed (least common, but cheap to try)
    cand.append(f"fake_{orig_fname}")
    # just basename prefixed
    cand.append(pref_b)
    # exact original (fallback)
    cand.append(orig_fname)
    # dedupe while preserving order
    seen = set(); out = []
    for c in cand:
        if c not in seen:
            seen.add(c); out.append(c)
    return out

def write_fired_counts(real_csv_path, fake_csv_path, out_counts_csv_path, error_list=None):
    """
    Reads real & fake activations CSVs, computes per-neuron 0.8×max threshold from real,
    and writes rows: filenames,real_count,fake_count
    """
    real_header, real_rows = load_csv_as_dicts(real_csv_path)
    fake_header, fake_rows = load_csv_as_dicts(fake_csv_path)

    real_fname_col = find_filename_column(real_header)
    fake_fname_col = find_filename_column(fake_header)

    neuron_cols = ensure_neuron_columns(real_header, n=64)

    # thresholds from real data
    threshold = compute_threshold_from_real(real_rows, neuron_cols, ratio=0.8)

    # index fake rows by their filename column
    fake_idx = { r[fake_fname_col]: r for r in fake_rows }

    with open(out_counts_csv_path, "w", newline="", encoding="utf-8") as f_out:
        w = csv.writer(f_out)
        w.writerow(["filenames", "real_count", "fake_count"])

        for r in real_rows:
            fname = r[real_fname_col]

            # real count
            try:
                real_vec = np.array([float(r[c]) for c in neuron_cols], dtype=np.float64)
                real_count = count_fired(real_vec, threshold)
            except Exception as e:
                if error_list is not None:
                    error_list.append({"stage":"count-real","item":fname,"error":f"{type(e).__name__}: {e}"})
                real_count = ""

            # fake count (match by filename with fake_ prefix heuristics)
            try:
                fr = None
                for key in _candidate_fake_keys(fname):
                    fr = fake_idx.get(key)
                    if fr is not None:
                        break
                if fr is None:
                    if error_list is not None:
                        error_list.append({"stage":"match-fake","item":fname,"error":"FileNotFoundError: fake row not found (tried fake_<basename> in-place, fake_<relpath>, and basename)"})
                    fake_count = ""
                else:
                    fake_vec = np.array([float(fr[c]) for c in neuron_cols], dtype=np.float64)
                    fake_count = count_fired(fake_vec, threshold)
            except Exception as e:
                if error_list is not None:
                    error_list.append({"stage":"count-fake","item":fname,"error":f"{type(e).__name__}: {e}"})
                fake_count = ""

            w.writerow([fname, real_count, fake_count])

    print(f"[done] wrote fired counts -> {out_counts_csv_path}")

In [22]:
# --- Step 8: run the comparison (0.8× rule) ---

REAL_ACT_CSV_PATH = "preds_of_64Neurons_denseLayer_test.csv"  # your file 1 (real)
FAKE_ACT_CSV_PATH = "[obj_labels_to_fakes]fake_activations(test).csv"                        # produced by process_class()
FIRED_COUNTS_CSV  = "[obj_labels_to_fakes]fired_counts_real_vs_fake(test).csv"               # output (3 cols)

# Reuse the same ERRORS list from earlier if you want to collect issues:
write_fired_counts(REAL_ACT_CSV_PATH, FAKE_ACT_CSV_PATH, FIRED_COUNTS_CSV, error_list=ERRORS)

# (optional) persist errors
if ERRORS:
    with open("pipeline_errors.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["stage","item","error"])
        w.writeheader(); w.writerows(ERRORS)
    print(f"[errors] wrote pipeline_errors.csv with {len(ERRORS)} entries")
else:
    print("[ok] no errors logged")

[done] wrote fired counts -> [obj_labels_to_fakes]fired_counts_real_vs_fake(test).csv
[ok] no errors logged

In [18]:
# --- Step 9: read confirmed neuron IDs (from your labels CSV) ---
import csv
import numpy as np
import os  

def _candidate_fake_keys(orig_fname):
    """
    Build possible keys for the fake CSV when fakes are named like 'fake_<original basename>.jpg'.
    Tries (in order):
      1) same dir, prefixed basename: 'dir/fake_name.jpg'
      2) whole relpath prefixed:      'fake_dir/name.jpg'
      3) just prefixed basename:      'fake_name.jpg'
      4) exact original:              'dir/name.jpg'
    """
    d = os.path.dirname(orig_fname)
    b = os.path.basename(orig_fname)
    pref_b = f"fake_{b}"

    cand = []
    cand.append(os.path.join(d, pref_b) if d else pref_b)
    cand.append(f"fake_{orig_fname}")
    cand.append(pref_b)
    cand.append(orig_fname)

    seen = set(); out = []
    for c in cand:
        if c not in seen:
            seen.add(c); out.append(c)
    return out


def load_confirmed_neuron_ids(confirmed_csv_path, id_col_candidates=("neuron_id","neuron","id")):
    """
    Returns a sorted list of unique confirmed neuron IDs (ints in [0,63]).
    """
    with open(confirmed_csv_path, "r", newline="", encoding="utf-8") as f:
        rdr = csv.DictReader(f)
        header = rdr.fieldnames or []

        # find the ID column
        id_col = None
        for c in id_col_candidates:
            if c in header:
                id_col = c
                break
        if id_col is None:
            raise RuntimeError(f"No neuron-id column found; looked for {id_col_candidates}")

        ids = []
        for row in rdr:
            try:
                j = int(float(row[id_col]))  # handle "12.0" too
                if 0 <= j <= 63:
                    ids.append(j)
            except Exception:
                # skip bad rows
                continue

        ids = sorted(set(ids))
        if not ids:
            raise RuntimeError("No valid confirmed neuron IDs (0..63) found.")
        return ids

In [24]:
# --- Step 10: confirmed-only fired counts using the 0.8× thresholds from REAL ---

def write_confirmed_fired_counts(real_csv_path,
                                 fake_csv_path,
                                 confirmed_csv_path,
                                 out_csv_path,
                                 ratio=0.8,
                                 error_list=None):
    """
    Reads:
      - real_csv_path: 64-neuron activations for real images
      - fake_csv_path: 64-neuron activations for fake images
      - confirmed_csv_path: subset of neuron IDs that are "confirmed" (with labels)
    Writes:
      - out_csv_path with columns: filenames, real_confirmed_count, fake_confirmed_count, total_confirmed_neurons
    """

    # Reuse helpers from Step 7; if you didn't run them, paste them above:
    #   load_csv_as_dicts, find_filename_column, ensure_neuron_columns,
    #   compute_threshold_from_real, count_fired

    # 1) load CSVs
    real_header, real_rows = load_csv_as_dicts(real_csv_path)
    fake_header, fake_rows = load_csv_as_dicts(fake_csv_path)

    real_fname_col = find_filename_column(real_header)
    fake_fname_col = find_filename_column(fake_header)

    neuron_cols = ensure_neuron_columns(real_header, n=64)

    # 2) thresholds from REAL (0.8× per-neuron max)
    threshold = compute_threshold_from_real(real_rows, neuron_cols, ratio=ratio)  # (64,)

    # 3) confirmed neuron IDs
    confirmed_ids = load_confirmed_neuron_ids(confirmed_csv_path)  # e.g., [3,7,12,...]
    confirmed_mask = np.zeros(64, dtype=bool)
    confirmed_mask[confirmed_ids] = True
    total_confirmed = int(np.sum(confirmed_mask))

        # 4) index fake rows by filename
    fake_idx = { r[fake_fname_col]: r for r in fake_rows }

    # 5) write counts
    with open(out_csv_path, "w", newline="", encoding="utf-8") as f_out:
        w = csv.writer(f_out)
        w.writerow(["filenames", "real_confirmed_count", "fake_confirmed_count", "total_confirmed_neurons"])

        for r in real_rows:
            fname = r[real_fname_col]

            # real confirmed count
            try:
                real_vec = np.array([float(r[c]) for c in neuron_cols], dtype=np.float64)
                real_count = int(np.sum(real_vec[confirmed_mask] >= threshold[confirmed_mask]))
            except Exception as e:
                if error_list is not None:
                    error_list.append({"stage":"count-real-confirmed","item":fname,"error":f"{type(e).__name__}: {e}"})
                real_count = ""

            # fake confirmed count (try fake_ prefix variants)
            try:
                fr = None
                for key in _candidate_fake_keys(fname):
                    fr = fake_idx.get(key)
                    if fr is not None:
                        break

                if fr is None:
                    if error_list is not None:
                        error_list.append({
                            "stage":"match-fake-confirmed",
                            "item":fname,
                            "error":"FileNotFoundError: fake row not found (tried fake_<basename> in dir, fake_<relpath>, basename, original)"
                        })
                    fake_count = ""
                else:
                    fake_vec = np.array([float(fr[c]) for c in neuron_cols], dtype=np.float64)
                    fake_count = int(np.sum(fake_vec[confirmed_mask] >= threshold[confirmed_mask]))
            except Exception as e:
                if error_list is not None:
                    error_list.append({"stage":"count-fake-confirmed","item":fname,"error":f"{type(e).__name__}: {e}"})
                fake_count = ""

            w.writerow([fname, real_count, fake_count, total_confirmed])

In [25]:
# --- Step 11: run confirmed-only counts ---

REAL_ACT_CSV_PATH = "preds_of_64Neurons_denseLayer_test.csv"      # your real activations (64 cols + filenames)
FAKE_ACT_CSV_PATH = "[obj_labels_to_fakes]fake_activations(test).csv"                            # produced earlier
CONFIRMED_CSV_PATH = "verification_summary_1 (test).csv"  # your uploaded file
CONFIRMED_COUNTS_OUT = "[obj_labels_to_fakes]fired_counts_confirmed_real_vs_fake(test).csv"      # new output

# Reuse shared ERRORS list if you want:
try:
    write_confirmed_fired_counts(
        real_csv_path=REAL_ACT_CSV_PATH,
        fake_csv_path=FAKE_ACT_CSV_PATH,
        confirmed_csv_path=CONFIRMED_CSV_PATH,
        out_csv_path=CONFIRMED_COUNTS_OUT,
        ratio=0.8,
        error_list=ERRORS  # optional
    )
except Exception as e:
    log_error("confirmed-counts", "aggregate", e)

# Optional: persist errors
if ERRORS:
    with open("pipeline_errors.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["stage","item","error"])
        w.writeheader(); w.writerows(ERRORS)
    print(f"[errors] wrote pipeline_errors.csv with {len(ERRORS)} entries")
else:
    print("[ok] no errors logged")

[ok] no errors logged

## statistical testing

In [27]:
# Wilcoxon (one-sided, paired) for: H_A = real_confirmed_count > fake_confirmed_count
# Requires: pip install scipy

import csv
import numpy as np
from scipy.stats import wilcoxon, rankdata

CSV_PATH = "[obj_labels_to_fakes]fired_counts_confirmed_real_vs_fake(test).csv"  # filenames, real_confirmed_count, fake_confirmed_count

# --- load paired counts ---
reals, fakes = [], []
with open(CSV_PATH, "r", newline="", encoding="utf-8") as f:
    rdr = csv.DictReader(f)
    for r in rdr:
        try:
            rv = float(r["real_confirmed_count"])
            fv = float(r["fake_confirmed_count"])
        except Exception:
            continue
        if np.isnan(rv) or np.isnan(fv):
            continue
        reals.append(rv); fakes.append(fv)

reals = np.asarray(reals, dtype=float)
fakes = np.asarray(fakes, dtype=float)
if reals.size == 0:
    raise RuntimeError("No valid (real,fake) pairs found in CSV. Check column names/values.")

diffs = reals - fakes  # test if diffs > 0  (i.e., fake < real)

# --- run Wilcoxon (zeros dropped by 'zero_method=wilcox') ---
stat, p = wilcoxon(diffs, alternative="greater", zero_method="wilcox", correction=False, mode="auto")

# --- descriptive stats ---
n_total   = diffs.size
nz_mask   = diffs != 0
n_nonzero = int(nz_mask.sum())
n_zero    = n_total - n_nonzero

med_real  = float(np.median(reals))
med_fake  = float(np.median(fakes))
med_diff  = float(np.median(diffs))
mean_diff = float(np.mean(diffs))
prop_pos  = float(np.mean(diffs > 0.0))  # proportion of pairs with real > fake (over all pairs)

# --- effect size: rank-biserial correlation (r_rb), on nonzero diffs only ---
if n_nonzero > 0:
    d_nz = diffs[nz_mask]
    ranks = rankdata(np.abs(d_nz), method="average")       # ranks of absolute diffs
    W_plus  = ranks[d_nz > 0].sum()
    W_minus = ranks[d_nz < 0].sum()
    denom = n_nonzero * (n_nonzero + 1) / 2.0
    r_rb = (W_plus - W_minus) / denom if denom > 0 else np.nan
else:
    r_rb = np.nan

# --- print report ---
print("=== Wilcoxon Signed-Rank Test (one-sided, real > fake) ===")
print(f"File: {CSV_PATH}")
print(f"N total pairs      : {n_total}")
print(f"N nonzero pairs    : {n_nonzero} (pairs used by Wilcoxon)")
print(f"N zero differences : {n_zero}")
print()
print(f"Median(real)       : {med_real:.3f}")
print(f"Median(fake)       : {med_fake:.3f}")
print(f"Median(diff)       : {med_diff:.3f}   (diff = real - fake)")
print(f"Mean(diff)         : {mean_diff:.3f}")
print(f"P(real > fake)     : {prop_pos:.3f}   (fraction of pairs with diff > 0 over all pairs)")
print()
print(f"Wilcoxon statistic : {stat:.6g}")
print(f"One-sided p-value  : {p:.6g}   (H_A: real > fake)")
print(f"Effect size r_rb   : {r_rb:.3f}   (rank-biserial correlation; -1..+1, >0 favors real)")
print("Decision (alpha=0.01): " + ("REJECT H0" if p < 0.01 else "fail to reject H0"))

=== Wilcoxon Signed-Rank Test (one-sided, real > fake) ===
File: [obj_labels_to_fakes]fired_counts_confirmed_real_vs_fake(test).csv
N total pairs      : 793
N nonzero pairs    : 221 (pairs used by Wilcoxon)
N zero differences : 572

Median(real)       : 0.000
Median(fake)       : 0.000
Median(diff)       : 0.000   (diff = real - fake)
Mean(diff)         : 0.149
P(real > fake)     : 0.183   (fraction of pairs with diff > 0 over all pairs)

Wilcoxon statistic : 16590
One-sided p-value  : 9.13903e-07   (H_A: real > fake)
Effect size r_rb   : 0.353   (rank-biserial correlation; -1..+1, >0 favors real)
Decision (alpha=0.01): REJECT H0

## FLUX .1 Pipeline

In [4]:
# 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

# !pip install huggingface-hub==0.25.2
# from huggingface_hub import login
# login()  # paste your HF token when prompted

import os
os.environ["HUGGINGFACE_HUB_TOKEN"] = "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"

In [7]:
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
import torch
from diffusers import FluxPipeline
import gc

gc.collect()
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()


# pipe = FluxPipeline.from_pretrained(
#     "black-forest-labs/FLUX.1-dev",
#     torch_dtype=torch.bfloat16,
# )

pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-schnell", torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()
pipe.enable_attention_slicing()

# Biggest memory saver:
pipe.enable_model_cpu_offload()

# Extra savers:
pipe.enable_attention_slicing()




FAKES_ROOT.mkdir(parents=True, exist_ok=True)

for i, row in manifest.iterrows():
    cls = row["class"]
    real_name = Path(row["real_path"]).name
    out_path = FAKES_ROOT / cls / f"fake_{real_name}"
    if out_path.exists():
        continue

    prompt = row["prompt"]

    img = pipe(prompt=prompt, guidance_scale=0.0, num_inference_steps=4,
               height=512, width=512, max_sequence_length=256).images[0]


    # keep your “<=500” save rule
    img = resize_for_saving(img, max_size=500)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path, quality=95)

print("Done generating fakes with FLUX.1-dev:", FAKES_ROOT)

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

2026-01-13 03:41:26.690803: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-13 03:41:26.728002: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-01-13 03:41:26.728049: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-01-13 03:41:26.728920: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-01-13 03:41:26.735200: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

2026-01-13 03:41:27.442714: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

model_index.json:   0%|          | 0.00/536 [00:00<?, ?B/s]

Fetching 23 files:   0%|          | 0/23 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/782 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/588 [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/4.53G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/705 [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.06M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/19.9k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/246M [00:00<?, ?B/s]

scheduler_config.json:   0%|          | 0.00/274 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/321 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

(…)pytorch_model-00003-of-00003.safetensors:   0%|          | 0.00/3.87G [00:00<?, ?B/s]

(…)ion_pytorch_model.safetensors.index.json:   0%|          | 0.00/121k [00:00<?, ?B/s]

(…)pytorch_model-00002-of-00003.safetensors:   0%|          | 0.00/9.95G [00:00<?, ?B/s]

(…)pytorch_model-00001-of-00003.safetensors:   0%|          | 0.00/9.96G [00:00<?, ?B/s]

config.json:   0%|          | 0.00/774 [00:00<?, ?B/s]

diffusion_pytorch_model.safetensors:   0%|          | 0.00/168M [00:00<?, ?B/s]

In [8]:
import os
k=0
for i in os.listdir("obj_labels_to_fakes"):
    d="obj_labels_to_fakes/"+i
    k+=len(os.listdir(d))
k

3158